### ISSUE TITLE
Is there a way to pass titles to the panels, so that each panel in the nav menu changes names according to where you are in the menu?

### ISSUE THREAD

**Issue by ericodes** [akreitals/angular-panel-snap#6]

**Comment by akreitals** [comment]
I am not quite sure I fully understand but each panel does have a `name` attribute which is what will be displayed in the menu.

Do you require that these names be bound such that if you were to change the a panels `name` that change is dynamically reflected in the menu?

**Comment by ericodes** [comment]
My mistake, I didn't see that. Thanks a lot for your prompt response!
